name: X Collector Worker


on:

  workflow_dispatch:


  schedule:

    # 北京时间06:30
    # UTC时间22:30
    - cron: "30 22 * * *"


    # 北京时间17:00
    # UTC时间09:00
    - cron: "0 9 * * *"



jobs:


  collector:


    runs-on: ubuntu-latest


    defaults:

      run:

        working-directory: collector



    steps:


      - name: Checkout repository

        uses: actions/checkout@v4



      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 22



      - name: Install dependencies

        run: npm install



      - name: Build project

        run: npm run build



      - name: Run collector

        run: npm start

        env:

          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
